### ISSUE TITLE
Create acceptance tests

### ISSUE THREAD

**Issue by LukeBMorrow** [gurtejboparai/bookwyrm#167]

**Comment by CameronJung** [comment]
I added a couple acceptance tests to the testing plan yesterday

**Comment by gurtejboparai** [comment]
@LukeBMorrow  Acceptance tests are written for all the user stories related to a user. Some are written by me and other by @CameronJung  . There are 3 more user stories left from the proposal that are related to journalist and author. I have not tested if those are functional yet.  Since, there will be no pull request for this issue, can you review it on the google doc and let us know if any changes are needed.

**Comment by LukeBMorrow** [comment]
The acceptance tests look good, I added the last ones needed. Did each of you execute them as you wrote them, or will we need to do that now?
